version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    extra_hosts:
      - "app.loc:127.0.0.1"
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    extra_hosts:
      - "api.app.loc:127.0.0.1"
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_DATABASE: MYSQLTEST
      MYSQL_USER: php-user
      MYSQL_PASSWORD: verysecuredsecret
      MYSQL_ROOT_PASSWORD: verysecuredsecretforroot
    networks:
      - app-network

  database:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: MYSQLTEST
      MYSQL_USER: php-user
      MYSQL_PASSWORD: verysecuredsecret
      MYSQL_ROOT_PASSWORD: verysecuredsecretforroot
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "app.loc:127.0.0.1"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge